services:
  - type: web
    name: xerox-center-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://yuvaraj18012008.github.io
      - key: JWT_SECRET
        generateValue: true
